[workspace]
resolver = "3"
members = ["crates/ai", "crates/agent", "crates/tool", "crates/logger"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[package]
name = "agent-tutorial"
version.workspace = true
edition.workspace = true

[dependencies]
ai = { path = "crates/ai" }
agent = { path = "crates/agent" }
tool = { path = "crates/tool" }
logger = { path = "crates/logger" }
anyhow = "1"
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
os_info = "3.15.0"
futures = "0.3"
tracing = "0.1"