[package]
name = "provider"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
logger = { path = "../logger" }
